jobs:
- job: Build_Windows_Binary

  pool:
    vmImage: 'windows-2019'

  steps:
    - powershell: choco install dotnetcore-sdk
      displayName: Install .NET Core 3.0

    - powershell:  dotnet publish -r win-x64 -c release 
      displayName: Build native Windows executable

    - powershell: cp ".\Humble Trove Console Downloader\bin\Release\netcoreapp3.0\win-x64\native\Humble Trove Console Downloader.exe" $(Build.ArtifactStagingDirectory)
      displayName: Copy Humble Trove Console Downloader to "Artifacts Staging Directory"

    - task: PublishBuildArtifacts@1
      displayName: Publish Windows executable
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: windows

- job: Build_Linux_Binary_1604
  
  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    dotnetUrl: 'https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb'

  steps:
    - script: 'sudo apt install -y liblttng-ust0 libssl1.0.0 libkrb5-3 zlib1g libicu55 wget clang-3.9 zlib1g-dev libkrb5-dev libcurl4-openssl-dev'
      displayName: Install dependencies
      
    - script: 'dotnet publish -r linux-x64 -c release'
      displayName: Build native Linux executable

    - script: 'cp "./Humble Trove Console Downloader/bin/Release/netcoreapp3.0/linux-x64/native/Humble Trove Console Downloader" $(Build.ArtifactStagingDirectory)'
      displayName: Copy Humble Trove Console Downloader to "Artifacts Staging Directory"

    - task: PublishBuildArtifacts@1
      displayName: Publish Linux executable
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: linux-ubuntu-1604

- job: Build_Linux_Binary_1804
  
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
    - script: 'sudo apt install -y liblttng-ust0 libssl1.0.0 libkrb5-3 zlib1g wget clang-3.9 zlib1g-dev libkrb5-dev libcurl4-openssl-dev'
      displayName: Install dependencies
      
    - script: 'dotnet publish -r linux-x64 -c release'
      displayName: Build native Linux executable

    - script: 'cp "./Humble Trove Console Downloader/bin/Release/netcoreapp3.0/linux-x64/native/Humble Trove Console Downloader" $(Build.ArtifactStagingDirectory)'
      displayName: Copy Humble Trove Console Downloader to "Artifacts Staging Directory"

    - task: PublishBuildArtifacts@1
      displayName: Publish Linux executable
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: linux-ubuntu-1804

- job: Build_MacOS
  
  pool:
    vmImage: 'macOS-10.14'

  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.0.100'
      inputs:
        packageType: sdk
        version: 3.0.100
        installationPath: $(Agent.ToolsDirectory)/dotnet
      
    - script: 'dotnet publish -r osx-x64 -c release'
      displayName: Build native macOS executable

    - script: 'cp "./Humble Trove Console Downloader/bin/Release/netcoreapp3.0/linux-x64/native/Humble Trove Console Downloader" $(Build.ArtifactStagingDirectory)'
      displayName: Copy Humble Trove Console Downloader to "Artifacts Staging Directory"

    - task: PublishBuildArtifacts@1
      displayName: Publish macOS executable
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: macos-high-sierra
