jobs:
- job: Build_Windows_Binary

  pool:
    vmImage: 'windows-2019'

  steps:
    - powershell: choco install dotnetcore-sdk
      displayName: Install .NET Core 3.0

    - powershell:  dotnet publish -r win-x64 -c release 
      displayName: Build native Windows executable

    - powershell: cp ".\Humble Trove Console Downloader\bin\Release\netcoreapp3.0\win-x64\native\Humble Trove Console Downloader.exe" $(Build.ArtifactStagingDirectory)
      displayName: Copy Humble Trove Console Downloader to "Artifacts Staging Directory"

    - task: PublishBuildArtifacts@1
      displayName: Publish Windows executable
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: winExe

- job: Build_Linux_Binary_1604
  
  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    dotnetUrl: 'https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb'

  steps:
    - script: 'sudo apt install -y wget'
      displayName: Install wget

    - script: 'wget $(dotnetUrl)'
      displayName: Download Microsoft repo

    - script: 'sudo dpkg -i packages-microsoft-prod.deb'
      displayName: Install Microsoft repo

    - script: 'sudo apt update'
      displayName: Update APT

    - script: 'sudo apt install apt-transport-https'
      displayName: Install APT HTTPS Transport

    - script: 'sudo apt update'
      displayName: Update APT (again)

    - script: 'sudo apt-get install dotnet-sdk-3.0'
      displayName: Install .NET SDK 3.0

    - script: 'dotnet publish -r linux-x64 -c release'
      displayName: Build native Linux executable

    - script: 'cp "./Humble Trove Console Downloader/bin/Release/netcoreapp3.0/linux-x64/native/Humble Trove Console Downloader" $(Build.ArtifactStagingDirectory)'
      displayName: Copy Humble Trove Console Downloader to "Artifacts Staging Directory"

    - task: PublishBuildArtifacts@1
      displayName: Publish Linux executable
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: linux-ubuntu-1604
